
modLoader="javafml" #mandatory

loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]]
modId="examplemod"
version="${file.jarVersion}"
displayName="A Stack Neko Modtweaker"
logoFile="asneko.png"
description='''
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.asnekotweak]]
    modId="forge" 
    mandatory=true 
    versionRange="[36,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.asnekotweak]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5)"
    ordering="NONE"
    side="BOTH"
